server:
  port: 8081

spring:
  application:
    name: produit
  datasource:
    url: jdbc:mysql://localhost:3306/produit_db
    username: root
    password: Neterusama123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

kafka:
  bootstrap-servers: localhost:9092
