server:
  port: 8083

spring:
  application:
    name: notification

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

kafka:
  bootstrap-servers: localhost:9092