server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: produit-service
          uri: http://localhost:8081
          predicates:
            - Path=/produits/**
        - id: commande-service
          uri: http://localhost:8082
          predicates:
            - Path=/commandes/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
