server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: produit
          uri: lb://produit
          predicates:
            - Path=/produits/**
        - id: commande
          uri: lb://commande
          predicates:
            - Path=/commandes/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
